### ISSUE TITLE
Fix kong config for get medication requests

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#4701]
Fix kong config for get medication requests

Align pattern for `  - name: manage-medication_requests`
```
            - methods:
                - GET
              path: >-
                /([0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}|[0]{4}-[0-9,A,E,H,K,M,P,T,X]{4}-[0-9,A,E,H,K,M,P,T,X]{4}-[0-9,A,E,H,K,M,P,T,X]{4})$
              scopes:
                - 'medication_request:details'
```
with real medication request number structure

Example:
`url: https://api.ehealth-ukraine.org/api/medication_requests/0000-75TM-E5MR-9795` doesn't match with this pattern
